version: "3"

services:

  app:
    container_name: application.container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database.container
      - DB_PASSWORD=root
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app
    command: "python main.py"
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    networks:
      - energie_vin-network

  postgres:
    container_name: database.container
    image: postgres:13.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5435:5432"
    networks:
      - energie_vin-network

networks:
  energie_vin-network: